[build]
  publish = "dist/spa"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
